### ISSUE TITLE
Help with Open Rally Computer, please!

### ISSUE THREAD

**Issue by HeadOfTheSPEDs** [mattogodoy/open-rally-computer#2]
@mattogodoy 

Hi Matias,
I'm hoping you've seen my email, tweet, and/or post on ADVRider. Even more so, hoping you might be willing to help me out just a bit on building your Open Rally Computer.

Thank you so much in advance/fingers crossed that you see this!

Relevant ADVRider post is at [https://www.advrider.com/f/threads/building-an-ico-checkmate-or-rallyemax-clone.1546305/#post-44420029](https://github.com/HeadOfTheSPEDs/reachingOut/issues/url).

**Comment by mattogodoy** [comment]
Email replied. Closing issue.
