### ISSUE TITLE
GPS Module in BOM

### ISSUE THREAD

**Issue by adrianhoffmann11** [mattogodoy/open-rally-computer#3]
I see that you have included the `uBlox Neo 6M breakout board module` in the [BOM](https://github.com/mattogodoy/open-rally-computer/blob/master/docs/pcb/bom/orc-bom.csv). However, based on your [blog post](https://matto.io/open-sourcing-the-baja-pro/#version-4) and PCB design, it appears that we should instead be using the `BN-180 GPS Module UART TTL` module. Which module is compatible with the PCB and code? Thanks!

**Comment by mattogodoy** [comment]
Hi!
Well spotted, sorry about that. The uBlox Neo 6M, 8M and the BN-180 GPS modules are all compatible, so you can use any of them with no changes in the firmware. My recommendation is the BN-180; gets satellites faster and has galileo compatibility.
I'll modify this in the BOM.
