### ISSUE TITLE
httpclient compile issue

### ISSUE THREAD

**Issue by iulianb0n** [mattogodoy/open-rally-computer#4]
Hi,

I just built the hardware for the open rally computer, wanted to program it, followed instructions and ended up with the issue that is further on. What could be the problem do you think?
Thank you!

Processing esp32dev (platform: espressif32; board: esp32dev; framework: arduino)
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------Verbose mode can be enabled via `-v, --verbose` option
CONFIGURATION: https://docs.platformio.org/page/boards/espressif32/esp32dev.html
PLATFORM: Espressif 32 (6.0.1) > Espressif ESP32 Dev Module
HARDWARE: ESP32 240MHz, 320KB RAM, 4MB Flash
DEBUG: Current (cmsis-dap) External (cmsis-dap, esp-bridge, esp-prog, iot-bus-jtag, jlink, minimodule, olimex-arm-usb-ocd, olimex-arm-usb-ocd-h, olimex-arm-usb-tiny-h, olimex-jtag-tiny, tumpa)
PACKAGES:
 - framework-arduinoespressif32 @ 3.20006.221224 (2.0.6)
 - tool-esptoolpy @ 1.40400.0 (4.4.0)
 - toolchain-xtensa-esp32 @ 8.4.0+2021r2-patch5
LDF: Library Dependency Finder -> https://bit.ly/configure-pio-ldf
LDF Modes: Finder ~ chain, Compatibility ~ soft
Found 41 compatible libraries
Scanning dependencies...
Dependency Graph
|-- U8g2 @ 2.26.1
|   |-- SPI @ 2.0.0
|   |-- Wire @ 2.0.0
|-- r89m Buttons @ 2.0.1
|-- r89m PushButton @ 1.0.0
|   |-- r89m Buttons @ 2.0.1
|   |-- Bounce2 @ 2.52
|-- TinyGPSPlus @ 1.0.2
|-- Time @ 1.5
|-- FRAM_MB85RC_I2C @ 0.0.0+20230307194407
|   |-- Wire @ 2.0.0
|-- Bounce2 @ 2.52
|-- Wire @ 2.0.0
|-- HTTPClient @ 2.0.0
|   |-- WiFi @ 2.0.0
|   |-- WiFiClientSecure @ 2.0.0
|   |   |-- WiFi @ 2.0.0
|   |-- Time @ 1.5
|-- Update @ 2.0.0
|-- WiFi @ 2.0.0
Building in debug mode
Compiling .pio\build\esp32dev\src\buttons.cpp.o
.
.
Compiling .pio\build\esp32dev\FrameworkArduino\FirmwareMSC.cpp.o
C:/Users/banic/.platformio/packages/framework-arduinoespressif32/libraries/HTTPClient/src/HTTPClient.cpp: In member function 'void HTTPClient::setCookie(String, String)':
C:/Users/banic/.platformio/packages/framework-arduinoespressif32/libraries/HTTPClient/src/HTTPClient.cpp:1554:15: error: aggregate 'tm tm' has incomplete type and cannot be defined
     struct tm tm;
               ^~
C:/Users/banic/.platformio/packages/framework-arduinoespressif32/libraries/HTTPClient/src/HTTPClient.cpp:1555:5: error: 'strptime' was not declared in this scope
     strptime(date.c_str(), HTTP_TIME_PATTERN, &tm);
     ^~~~~~~~
C:/Users/banic/.platformio/packages/framework-arduinoespressif32/libraries/HTTPClient/src/HTTPClient.cpp:1555:5: note: suggested alternative: 'st_ctime'
     strptime(date.c_str(), HTTP_TIME_PATTERN, &tm);
     ^~~~~~~~
     st_ctime
C:/Users/banic/.platformio/packages/framework-arduinoespressif32/libraries/HTTPClient/src/HTTPClient.cpp:1556:19: error: 'mktime' was not declared in this scope
     cookie.date = mktime(&tm);
                   ^~~~~~
C:/Users/banic/.platformio/packages/framework-arduinoespressif32/libraries/HTTPClient/src/HTTPClient.cpp:1556:19: note: suggested alternative: 'mktemp'
     cookie.date = mktime(&tm);
                   ^~~~~~
                   mktemp
C:/Users/banic/.platformio/packages/framework-arduinoespressif32/libraries/HTTPClient/src/HTTPClient.cpp:1643:24: error: 'time' was not declared in this scope
     time_t now_local = time(NULL);
                        ^~~~
C:/Users/banic/.platformio/packages/framework-arduinoespressif32/libraries/HTTPClient/src/HTTPClient.cpp:1643:24: note: suggested alternative: 'tone'
     time_t now_local = time(NULL);
                        ^~~~
                        tone
C:/Users/banic/.platformio/packages/framework-arduinoespressif32/libraries/HTTPClient/src/HTTPClient.cpp:1644:29: error: 'gmtime' was not declared in this scope
     time_t now_gmt = mktime(gmtime(&now_local));
                             ^~~~~~
C:/Users/banic/.platformio/packages/framework-arduinoespressif32/libraries/HTTPClient/src/HTTPClient.cpp:1644:29: note: suggested alternative: 'getSize'
     time_t now_gmt = mktime(gmtime(&now_local));
                             ^~~~~~
                             getSize
C:/Users/banic/.platformio/packages/framework-arduinoespressif32/libraries/HTTPClient/src/HTTPClient.cpp: In member function 'bool HTTPClient::generateCookieString(String*)':
C:/Users/banic/.platformio/packages/framework-arduinoespressif32/libraries/HTTPClient/src/HTTPClient.cpp:1670:24: error: 'time' was not declared in this scope
     time_t now_local = time(NULL);
                        ^~~~
C:/Users/banic/.platformio/packages/framework-arduinoespressif32/libraries/HTTPClient/src/HTTPClient.cpp:1670:24: note: suggested alternative: 'tone'
     time_t now_local = time(NULL);
                        ^~~~
                        tone
C:/Users/banic/.platformio/packages/framework-arduinoespressif32/libraries/HTTPClient/src/HTTPClient.cpp:1671:29: error: 'gmtime' was not declared in this scope
     time_t now_gmt = mktime(gmtime(&now_local));
                             ^~~~~~
C:/Users/banic/.platformio/packages/framework-arduinoespressif32/libraries/HTTPClient/src/HTTPClient.cpp:1671:29: note: suggested alternative: 'getSize'
     time_t now_gmt = mktime(gmtime(&now_local));
                             ^~~~~~
                             getSize
C:/Users/banic/.platformio/packages/framework-arduinoespressif32/libraries/HTTPClient/src/HTTPClient.cpp:1671:22: error: 'mktime' was not declared in this scope
     time_t now_gmt = mktime(gmtime(&now_local));
                      ^~~~~~
C:/Users/banic/.platformio/packages/framework-arduinoespressif32/libraries/HTTPClient/src/HTTPClient.cpp:1671:22: note: suggested alternative: 'mktemp'
     time_t now_gmt = mktime(gmtime(&now_local));
                      ^~~~~~
                      mktemp
Compiling .pio\build\esp32dev\FrameworkArduino\FunctionalInterrupt.cpp.o
*** [.pio\build\esp32dev\libec6\HTTPClient\HTTPClient.cpp.o] Error 1

**Comment by mattogodoy** [comment]
Hello!

It seems like the HTTPClient library is complaining.
My guess is that because this project is now 2 years old, that library must have been updated, and this code is no longer compatible.

Sadly I don't have the time to take a look into it, but it should not be a difficult fix to make.
The HTTPClient library is used to check if a new version of the firmware is online, but since I'm not pushing new versions since 2 years ago it's not useful right now. You could even comment out the parts of the code that use it (in https://github.com/mattogodoy/open-rally-computer/blob/master/src/ota.cpp).

If you decide to fix it instead of commenting out your code, I'd appreciate a Pull Request to merge the fix into this project.
Thanks a good luck!

**Comment by iulianb0n** [comment]
Thank you for the response and temporary fix, will have a go at doing a full fix, once I understand what needs to be done(almost complete noob at this).

**Comment by mattogodoy** [comment]
No problem! Have fun :)
