### ISSUE TITLE
fork and license?

### ISSUE THREAD

**Issue by pcace** [mattogodoy/open-rally-computer#6]
Hi there, i have found your wonderful ORC project. since some time i have played around using my own fork. changed bits here and there. now i am wondering - can i do that in terms of license ( it is just a private  playground for me, with no intention to make any money or whatsoever from it)? in all files there is a (c) 2021 Matías Godoy. 
If i need to add or remove anything from my files, please let me know!! (https://github.com/pcace/open-rally-computer/tree/dev)
the changes i made to the code are: 
- use different display and library
-use sd card for memory (i know fram is much more reliable, but i just had non laying around...) 
- use sd card for recording track
- add webserver wich provides recorded tracks
- add 2d Compass in the heading menu
- read voltage from voltage devider and add to status bar
- add "save-POI" function when in "track" page

and thanks again for this awesome project!!

**Comment by mattogodoy** [comment]
Hi there!
First of all, I wanted to thank you for asking. Not many people think of these things, and they are important in the open-source world :)

A brief summary of [the license I've set for this project](https://github.com/mattogodoy/open-rally-computer?tab=GPL-3.0-1-ov-file#readme) is that you can do whatever you want with it, even make money! The only condition is that you have to keep your variant of the project along with all of your changes open-source and available to anyone who wants to see or use it for themselves. You cannot make a close-sourced variant of this project.

As far as I can see, you are already complying as your repo is public and I can see all your changes, which by the way are really good additions to the project!

If you have pictures of your changes (how the device looks, how the tracks look, etc) and can add them here, it would make me really happy to see them. It brings me a lot of joy knowing that the project is being useful to someone else. Especially knowing that people are customizing it and adding more features 🙌🏻 

Best of luck, and I hope you enjoy your Open Rally Computer 🚀

**Comment by pcace** [comment]
Hi, thanks for your warm reply! i will definitely update the readme.md in the next days reflecting the changes i have made to the code, and try to make some ok pictures of the cable-mess i have created here ;) Like i said - it is more a playground for me then the goal to have a bullet prove rally computer ( although it already did around 2000km on my WR450 with my codebase and worked pretty good ;) )

**Comment by pcace** [comment]
updated the manual and readme 
https://github.com/pcace/open-rally-computer/commit/42198d1d75e1d2708391b3459bd140808c60dbc8

when i find some more time, i will go through it more in depth!
